POST http://localhost:3000/api/blogs
content-type: application/json

{
    "title": "ttttttt",
    "author": "-ttttttttt--",
    "url": "kappa.com",
    "likes": "2"
}

###

GET  http://localhost:3000/api/blogs

