POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Some name",
    "username": "someOtherUsername",
    "password": "12345678"
}

###

GET http://localhost:3000/api/users
